server:
  port: 8090

spring:
  application:
    name: msvc-barmacia
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/barmaciaDb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: locahost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka